[package]
name = "list_comprehension"
version = "0.1.2"
edition = "2021"

description = "A macro for Haskell-like list comprehensions in Rust."
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/ANIDENTIFIER/list_comprehension"


[dependencies]
